version: '3.8'

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles-aws/Dockerfile.aws_backend
    ports:
      - "8000:8000"
    env_file:
      - ./full-stack/backend/.env
    volumes:
      - static_volume:/staticfiles/
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfiles-aws/Dockerfile.aws_nginx
    volumes:
      - static_volume:/staticfiles/
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume: