# Generated by Django 4.2.10 on 2024-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, default='logo-placeholder', upload_to='logos/'),
        ),
    ]
