# Generated by Django 4.2.10 on 2024-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centers', '0002_alter_church_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
