# Generated by Django 4.2.9 on 2024-01-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claimscounter_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimscounter',
            options={'verbose_name_plural': 'Counter'},
        ),
    ]
