name: CI/CD Pipeline

on:
  push:
    branches: [ test ]
    paths-ignore:
      - README.md
      - .gitignore
      - readme-images/**
      # - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
  
      - name: Run backend tests
        env:
          SECRET_KEY: ${{ secrets.DJANGO_TEST_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASS: ${{ secrets.EMAIL_HOST_PASS }}
          BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          NO_HTTPS: ${{ secrets.NO_HTTPS }}

        run: |
          cd backend
          python manage.py test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Heroku (backend)
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_BACKEND_NAME_TEST}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "backend"
        dontautocreate: true

    - name: Deploy to Heroku (frontend)
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_FRONTEND_NAME_TEST}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "frontend"
        dontautocreate: true